# Options applicable to Docker
docker_options:
  
  # These are all the daemons we can start Docker containers with
  daemons:
    - 'boot2docker'
  
  # The image - must be in the local repository
  image: andytinycat/ncat
  
  # The command to be run - if absent, will run whatever the image specifies
  docker_cmd: [ 'ncat', -l, '12345', -k, -c, 'xargs -n1 echo']

  # Port to expose - we can only expose one port as we only proxy one port
  expose: 12345/tcp

ganger_options:
  
  # Listen on this port for client connections
  listen_port: 5454
  
  # Try to connect immediately after starting the container, then
  # 6 more times, with a timeout of 5 seconds
  service_connection_timeout: 5
  service_connection_retries: 6
  
  # Wait 300 seconds for Docker to respond (image pulls can be slow!)
  docker_timeout: 300